### ISSUE TITLE
Reduce GIT configuration steps number.

### ISSUE THREAD

**Issue by polubelova** [YaccConstructor/YaccConstructor#5]
WTF? Why should I specify git user name and password in more then one place to reset git repo?
1) .Fsx script
2) VCS root configuration
3) "Git set user" build step
4) ... 

These parameters should be placed in one config.

**Comment by gsvgit** [comment]
@raymon-02 , really, WTF?

**Comment by raymon-02** [comment]
Why WTF?
You don't need to change user name and password in more than one place:
1) .fsx script: only ref to repo (we have more than one repo, that's why it must be specify). And it happens because we've moved our repo to GitHub
2) VCS root configuration: only user name and password. The same story. And general user has different passwords to different repos.
3) Git set user: you don't have to change it. It's only for commit story (but this field cannot be empty).
Another case is if you really want to change user name, you will have to change user name in triggers. Otherwise building will be run infinitely.

**Comment by raymon-02** [comment]
I fixed some things: now there is no need to change user name and password for every build configuration (if unexpectedly user name and password have been really changed due to some unbelivieble occasions). All these stuff (user name, email..) are in General Parameters. So you need to change only these ones (yes, in one place).
I added these parameters in all build configurations.

Close and comment? Or still WTF?

**Comment by gsvgit** [comment]
Well. Is it possible to specify TC environment variables for user, password, and URL and use them everywhere? Moreover, seems that some of variables should available  immediately after VCS  root configuration. All variables can be passed to scripts as parameters.

**Comment by raymon-02** [comment]
Yes, it is possible. I changed scripts: now values of user, password and URL are taken from TC environment variables. So there is no need to specify user and password in bat file.
User and password are common for all configuarions, but URL is specified for every configuration as repos can be different.
