### ISSUE TITLE
Merge RegApproximation into dev

### ISSUE THREAD

**Issue by gsvgit** [YaccConstructor/YaccConstructor#9]
Merge RegApproximation into dev and remove RegApproximation branch.

**Comment by octomarat** [comment]
I have merged RegApproximation and now dev CI tests fail. The solution is built with no errors on my laptop, so I don't understand what is the reason of these fails (I don't have an experience working with TeamCity).

**Comment by gsvgit** [comment]
Well... Stay in your branch (RegApproximation) and continue working. Seems we have problems with git configuration.

**Comment by octomarat** [comment]
= ) I have already removed RegApproximation branch. Would it be okey to just create new one from dev?

**Comment by gsvgit** [comment]
Yes.

**Comment by gsvgit** [comment]
@octomarat , try to merge RegApproximation into dev when final version will be ready. All minor fixes in future should be done directly in dev.

**Comment by gsvgit** [comment]
@octomarat  what about merging? May you merge this branch into dev and continue development in dev branch (or other appropriate branch)?

**Comment by octomarat** [comment]
We have merged RegApproximation into migrate_R# branch with @IvanovAndrew. When I'l finish separating my code there, migrate_R# can be merged in dev.
If fact, there are some problems with merging already. My branch works with .NET 4, migrate_R# works with .NET 4.5 (I suppose dev too). For now we can't run any tests for approximation, because after moving to .NET 4.5 they all fail with strange exception (something has changed in ReSharper testing environment).
So I still make changes in my branch, test them and then add the changes to migrate_R#.

**Comment by octomarat** [comment]
Branch merged into dev and removed
